modid = "midas"
name = "Midas"
description = "Midas is a economy mod, meant to facilitate and assist trade in game."
version = "0.1.0"
url = "https://example.com"
author = "Cptlsthjhg"
credits = "Credit to contributors: Cptlsthjhg, Fabulous_Shrub."

[[dependencies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"